<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.0.0.379
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Envío de Formulario Contacto',
	'heading' => 'Envío de nuevo formulario',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Marcada',
		'checkbox_unchecked' => 'No marcada',
		'submitted_from' => 'Formulario enviado desde el sitio web: %s',
		'submitted_by' => 'Dirección IP del visitante: %s',
		'too_many_submissions' => 'Se han realizado recientemente demasiados envíos a través de esta IP',
		'failed_to_send_email' => 'Error al enviar el correo electrónico',
		'invalid_reCAPTCHA_private_key' => 'Clave privada de reCAPTCHA no válida.',
		'invalid_reCAPTCHA2_private_key' => 'Clave privada de reCAPTCHA 2.0 no válida.',
		'invalid_reCAPTCHA2_server_response' => 'Respuesta de servidor de reCAPTCHA 2.0 no válida.',
		'invalid_field_type' => 'Tipo de campo desconocido: %s.',
		'invalid_form_config' => 'El campo \'%s\' contiene una configuración no válida.',
		'unknown_method' => 'Método de solicitud de servidor desconocido'
	),
	'email' => array(
		'from' => 'contacto@volveravivirlibre.com',
		'to' => 'contacto@volveravivirlibre.com'
	),
	'fields' => array(
		'custom_U8562' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Nombre',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Nombre\' es obligatorio.'
			)
		),
		'Email' => array(
			'order' => 4,
			'type' => 'email',
			'label' => 'tú correo electrónico',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'tú correo electrónico\' es obligatorio.',
				'format' => 'El campo \'tú correo electrónico\' contiene un correo electrónico no válido.'
			)
		),
		'custom_U8570' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Comentarios',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'COmentarios\' es obligatorio.'
			)
		),
		'custom_U8566' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Estado',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Estado\' es obligatorio.'
			)
		),
		'custom_U8574' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Número  de Teléfono',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Número  de Teléfono\' es obligatorio.'
			)
		),
		'custom_U8580' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Ciudad',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Ciudad\' es obligatorio.'
			)
		)
	)
);

process_form($form);
?>
